apiVersion: v2
dependencies:
- name: metallb
  repository: https://metallb.github.io/metallb
  version: 0.14.5
description: |
  This chart installs and configures metallb.
  For more information check the following link:
  https://metallb.universe.tf/
name: metallb
version: "0"
